const options = [
  { value: 'Todos os departamentos', label: 'Todos os departamentos' },
  { value: 'Alexa Skills', label: 'Alexa Skills' },
  { value: 'Alimentos e Bebidas', label: 'Alimentos e Bebidas' },
  { value: 'Amazon Quase Novo', label: 'Amazon Quase Novo' },
  { value: 'Apps e Jogos', label: 'Apps e Jogos' },
  { value: 'Audiolivros Audible', label: 'Audiolivros Audible' },
  { value: 'Automotivo', label: 'Automotivo' },
  { value: 'Bebês', label: 'Bebês' },
  { value: 'Beleza', label: 'Beleza' },
  { value: 'Beleza de Luxo', label: 'Beleza de Luxo' },
  { value: 'Bolsas, Malas e Mochilas', label: 'Bolsas, Malas e Mochilas' },
  { value: 'Brinquedos e Jogos', label: 'Brinquedos e Jogos' },
  { value: 'Casa', label: 'Casa' },
  { value: 'Cd e Vinil', label: 'Cd e Vinil' },
  { value: 'Computadores e Informática', label: 'Computadores e Informática' },
  { value: 'Cozinha', label: 'Cozinha' },
  { value: 'Dispositivos Amazon', label: 'Dispositivos Amazon' },
  { value: 'DVD e Blue-Ray', label: 'DVD e Blue-Ray' },
  { value: 'Eletrodoésticos', label: 'Eletrodomésticos' },
  { value: 'Eletrônicos', label: 'Eletrônicos' },
  { value: 'Esportes e Aventura', label: 'Esportes e Aventura' },
  {
    value: 'Ferramentas e Materiais de Construção',
    label: 'Ferramentas e Materiais de Construção',
  },
  { value: 'Games', label: 'Games' },
  { value: 'Instrumentos Musicais', label: 'Instrumentos Musicais' },
  { value: 'Jardim e Piscina', label: 'Jardim e Piscina' },
  { value: 'Livros', label: 'Livros' },
  { value: 'Loja Kindle', label: 'Loja Kindle' },
  { value: 'Material para Escritório e Papelaria', label: 'Material para Escritório e Papelaria' },
  { value: 'Móveis e Decoração', label: 'Moveis e Decoração' },
  { value: 'Pet Shop', label: 'Pet Shop' },
  { value: 'Prime Video', label: 'Prime Video' },
  { value: 'Produtos Industriais e Científicos', label: 'Produtos Industriais e Científicos' },
  { value: 'Progame e Poupe', label: 'Programe e Poupe' },
  { value: 'Roupas, Calçados e Joias', label: 'Roupas, Calçados e Joias' },
  { value: 'Feminino', label: 'Feminino' },
  { value: 'Masculino', label: 'Masculino' },
  { value: 'Meninas', label: 'Meninas' },
  { value: 'Meninos', label: 'Meninos' },
  { value: 'Bebês', label: 'Bebês' },
  { value: 'Saúde e Cuidados Pessoais', label: 'Saúde e Cuidados Pessoais' },
];

export default options;
